data:
  train_path: /root/wjl/data/NavierStokes_V1e-5_N1200_T20.mat
  test_path: /root/wjl/data/NavierStokes_V1e-5_N1200_T20.mat 
  ntrain: 1000
  ntest: 100
  nx: 16
  sub: 4
  # nx = 64//sub
  t_in: 5
  t: 3
  batch_size: 10

model:
  name: fno3d
  modes1: 4
  modes2: 4
  modes3: 4
  width: 20

train:
  mix_prec: true
  epoch: 500
  base_lr: 1.e-3
  weight_decay: 1.e-4
  scheduler_gamma: 0.5
  decay_per_epoch: 100
  # load_path: ckpt/ms/fno3d_pretrain.ckpt
  save_per_epoch: 100
  save_path: ckpt/ms/fno3d_pretrain
  # save_path: ckpt/torch/fno3d_pretrain_mix
  profile: false
  profiler_path: ./profiler

test:
  load_path: ckpt/ms/fno3d_pretrain.ckpt

