data:
  train_path: ./data/piececonst_r421_N1024_smooth1.mat
  test_path: ./data/piececonst_r421_N1024_smooth2.mat
  total_num: 1024
  offset: 0
  ntrain: 1000
  ntest: 100
  nx: 421
  sub: 30
  f_weight: 1.0
  data_weight: 5.0
  batch_size: 20

model:
  name: pino2d
  layers: [64, 64, 64, 64, 64]
  modes1: [4, 4, 4, 4]
  modes2: [4, 4, 4, 4]
  fc_dim: 128
  activation: gelu

train:
  mix_prec: true
  epoch: 5
  base_lr: 0.001
  weight_decay: 1.e-4
  scheduler_gamma: 0.5
  decay_per_epoch: 50
  # load_path: ckpt/ms/pino2d_pretrain.ckpt
  profile: true
  profiler_path: ./profiler/pino2d
